# Generated by Django 2.2.7 on 2019-11-15 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Description')),
                ('company', models.CharField(blank=True, max_length=100, null=True, verbose_name='Company')),
                ('cnpj', models.CharField(blank=True, max_length=38, null=True, verbose_name='CNPJ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
        ),
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('is_default', models.CharField(max_length=1, verbose_name='Is it defalt?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('is_default', models.CharField(max_length=1, verbose_name='Is it defalt?')),
            ],
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('reference_date', models.DateField(verbose_name='Reference date')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Value')),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Value')),
                ('payment_date', models.DateField(verbose_name='Reference date')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Value')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('id_broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Broker')),
                ('id_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Type')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(max_length=1, verbose_name='Operation type')),
                ('amount', models.IntegerField(verbose_name='Amount')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Value')),
                ('brokerrate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Broker rate')),
                ('balance', models.CharField(max_length=1, verbose_name='Balance of this asset is + or -')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Asset')),
                ('id_broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Broker')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Emolument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Value')),
                ('id_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Balance value')),
                ('tax_to_pay', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Tax to pay')),
                ('type_operation', models.CharField(max_length=1, verbose_name='Is it defalt?')),
                ('reference_date', models.DateField(verbose_name='Reference date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('id_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Type')),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='id_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Type'),
        ),
    ]
