# Generated by Django 2.2.7 on 2019-11-15 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.SlugField(max_length=30, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='broker',
            name='name',
            field=models.SlugField(max_length=30, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.SlugField(max_length=100, verbose_name='Name'),
        ),
    ]
