# Generated by Django 2.2.7 on 2019-11-23 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='is_default',
            field=models.CharField(blank=True, choices=[('1', 'Default'), ('0', '')], max_length=1, null=True),
        ),
    ]
