# Generated by Django 2.2.7 on 2019-12-01 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_type_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='balance',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='broker',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='emolument',
            options={'ordering': ['id_order']},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='tax',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='type',
            name='is_default',
            field=models.CharField(blank=True, choices=[('1', 'Yes'), ('0', 'No')], default='0', max_length=1, null=True, verbose_name='Default'),
        ),
    ]
