# Generated by Django 2.2.7 on 2019-12-03 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20191130_2127'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Type',
            new_name='AssetType',
        ),
    ]
