# Generated by Django 2.2.7 on 2019-12-04 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20191203_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assettype',
            name='name',
            field=models.SlugField(max_length=100, verbose_name='Name'),
        ),
    ]
