# Generated by Django 2.2.7 on 2019-12-06 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_dividendyield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dividendyield',
            name='created_at',
        ),
        migrations.AddField(
            model_name='dividendyield',
            name='paid_in',
            field=models.DateField(auto_now=True, verbose_name='Paid in'),
        ),
    ]
