# Generated by Django 2.2.7 on 2019-12-06 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20191205_2317'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dividendyield',
            unique_together=set(),
        ),
    ]
