# Generated by Django 2.2.7 on 2019-12-08 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20191205_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dividendyield',
            name='paid_in',
            field=models.DateField(verbose_name='Paid in'),
        ),
    ]
