# Generated by Django 2.2.7 on 2019-12-08 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20191207_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='cnpj',
            field=models.CharField(blank=True, max_length=38, null=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='assettype',
            name='is_default',
            field=models.CharField(blank=True, choices=[('y', 'Yes'), ('n', 'No')], default='0', max_length=1, null=True, verbose_name='Default'),
        ),
        migrations.AlterField(
            model_name='broker',
            name='is_default',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No')], default='n', max_length=1, verbose_name='Is it defalt?'),
        ),
    ]
