# Generated by Django 2.2.7 on 2019-12-08 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0017_auto_20191207_2342'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerRateRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biggerthan', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Bigger than')),
                ('lessthan', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Less than')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Broker rate')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Order')),
            ],
        ),
        migrations.CreateModel(
            name='BrokerRateRuleAsseTypeBroker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assettype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.AssetType')),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Broker')),
                ('brokerraterule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.BrokerRateRule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
