# Generated by Django 2.2.7 on 2019-12-08 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0021_auto_20191208_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerRateRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordertype', models.CharField(choices=[('d', 'Daytrade'), ('n', 'Normal')], max_length=1, verbose_name='Order type')),
                ('biggerthan', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Bigger than')),
                ('lessthan', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Less than')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Broker rate')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BrokerRateRuleAsseTypeBroker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assettype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.AssetType')),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Broker')),
                ('brokerraterule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.BrokerRateRule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
