# Generated by Django 2.2.7 on 2019-12-14 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20191208_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brokerraterule',
            name='biggerthan',
        ),
        migrations.AddField(
            model_name='brokerraterule',
            name='greaterthan',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Greater than'),
        ),
    ]
