# Generated by Django 2.2.7 on 2019-12-14 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20191214_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brokerraterule',
            name='greaterthan',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Greater than'),
        ),
    ]
