# Generated by Django 2.2.7 on 2019-12-14 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20191214_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brokerraterule',
            name='greaterthan',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Greater than'),
        ),
        migrations.AlterField(
            model_name='brokerraterule',
            name='lessthan',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Less than'),
        ),
    ]
