# Generated by Django 2.2.7 on 2019-12-22 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0028_auto_20191214_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='YieldType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Yield type')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='dividendyield',
            name='yield_typpe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.YieldType'),
        ),
    ]
