# Generated by Django 2.2.7 on 2019-12-22 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20191222_0751'),
    ]

    operations = [
        migrations.AddField(
            model_name='yieldtype',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Created at'),
        ),
        migrations.AddField(
            model_name='yieldtype',
            name='is_default',
            field=models.CharField(blank=True, choices=[('y', 'Yes'), ('n', 'No')], default='0', max_length=1, null=True, verbose_name='Default'),
        ),
    ]
