# Generated by Django 2.2.7 on 2019-12-22 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20191222_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yieldtype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
    ]
