# Generated by Django 2.2.7 on 2019-12-22 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20191222_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assettype',
            name='is_default',
            field=models.CharField(blank=True, choices=[('y', 'Yes'), ('n', 'No')], default='n', max_length=1, null=True, verbose_name='Default'),
        ),
        migrations.AlterField(
            model_name='yieldtype',
            name='is_default',
            field=models.CharField(blank=True, choices=[('y', 'Yes'), ('n', 'No')], default='n', max_length=1, null=True, verbose_name='Default'),
        ),
    ]
