# Generated by Django 2.2.7 on 2020-01-01 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20191222_0822'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['code']},
        ),
        migrations.RemoveField(
            model_name='asset',
            name='company',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='description',
        ),
        migrations.AddField(
            model_name='asset',
            name='code',
            field=models.SlugField(default='X', max_length=30, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Corporate name'),
        ),
    ]
