# Generated by Django 2.2.7 on 2020-01-02 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20200101_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='balance',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Balance of this asset is + or -'),
        ),
    ]
