# Generated by Django 2.2.7 on 2020-01-02 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_auto_20200101_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='brokerrate',
            field=models.FloatField(verbose_name='Broker rate'),
        ),
        migrations.AlterField(
            model_name='order',
            name='value',
            field=models.FloatField(verbose_name='Value'),
        ),
    ]
