# Generated by Django 2.2.7 on 2020-01-03 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_auto_20200101_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='balance',
        ),
        migrations.AddField(
            model_name='order',
            name='emolument',
            field=models.FloatField(blank=True, null=True, verbose_name='Emolument'),
        ),
        migrations.AddField(
            model_name='order',
            name='tax',
            field=models.FloatField(blank=True, null=True, verbose_name='ISS + PIS + CONFINS'),
        ),
        migrations.AlterField(
            model_name='order',
            name='operation_type',
            field=models.CharField(choices=[('b', 'Buy'), ('s', 'Sale'), ('r', 'Rent')], max_length=1, verbose_name='Operation type'),
        ),
        migrations.DeleteModel(
            name='Emolument',
        ),
    ]
