# Generated by Django 2.2.7 on 2020-01-04 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_remove_order_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brokerraterule',
            name='ordertype',
            field=models.CharField(choices=[('d', 'Daytrade'), ('n', 'Normal'), ('r', 'Rent')], max_length=1, verbose_name='Order type'),
        ),
    ]
