# Generated by Django 2.2.7 on 2020-01-14 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_auto_20200113_2057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['updated_at']},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='created_at',
            new_name='operated_at',
        ),
    ]
