# Generated by Django 2.2.7 on 2020-01-14 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_auto_20200113_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='operated_at',
            field=models.DateField(verbose_name='Operation time'),
        ),
    ]
