# Generated by Django 2.2.7 on 2020-03-21 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_auto_20200321_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='emolument',
            field=models.FloatField(default=0, verbose_name='Emolument'),
        ),
    ]
