# Generated by Django 2.2.7 on 2020-03-31 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_auto_20200321_1749'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='value',
            new_name='balance',
        ),
    ]
