# Generated by Django 3.0.1 on 2020-05-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_auto_20200331_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='balance',
            field=models.FloatField(verbose_name='Balance'),
        ),
    ]
