# Generated by Django 3.0.1 on 2020-05-05 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_auto_20200502_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='regarding_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Regarding at'),
        ),
    ]
