# Generated by Django 3.0.1 on 2020-05-05 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_position_regarding_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='regarding_at',
            field=models.DateTimeField(verbose_name='Regarding at'),
        ),
    ]
