# Generated by Django 3.0.1 on 2021-12-19 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0052_auto_20200504_2156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(verbose_name='Balance')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Asset')),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Broker')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.AssetType')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
