# Generated by Django 3.0.1 on 2021-12-19 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='asset',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Asset'),
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
