# Generated by Django 3.0.1 on 2021-12-19 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_auto_20211219_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Asset'),
        ),
    ]
