# Generated by Django 3.0.1 on 2021-12-19 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_auto_20211219_1357'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['regarding_at']},
        ),
        migrations.AlterField(
            model_name='position',
            name='regarding_at',
            field=models.DateField(verbose_name='Regarding at'),
        ),
    ]
