# Generated by Django 3.0.1 on 2022-01-01 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0056_auto_20211219_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_diversified', models.FloatField(verbose_name='Risk Diversified')),
                ('risk_systemic', models.FloatField(verbose_name='Risk Systemic')),
                ('regarding_at', models.DateField(verbose_name='Regarding at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['regarding_at'],
            },
        ),
        migrations.CreateModel(
            name='WalletAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amuont', models.FloatField(verbose_name='Amount')),
                ('balance', models.FloatField(verbose_name='Balance')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Asset')),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Broker')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Wallet')),
            ],
        ),
    ]
